services:
  # Frontend service (ReactJS)
  frontend:
    build:
      context: D:/APP_QUANLYTAICHINH/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # Backend service (Laravel)
  backend:
    build:
      context: D:/APP_QUANLYTAICHINH/backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password

  # Web server (Nginx)
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - D:/App_QuanLyTaiChinh/backend:/var/www
    depends_on:
      - backend
      - frontend

  # Database service (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
